In [ ]:
%pip install sqlalchemy pymysql pandas

Requirement already satisfied: sqlalchemy in .\curve\lib\site-packages (2.0.45)
Requirement already satisfied: pymysql in .\curve\lib\site-packages (1.1.2)
Requirement already satisfied: pandas in .\curve\lib\site-packages (2.3.3)
Requirement already satisfied: greenlet>=1 in .\curve\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in .\curve\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in .\curve\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in .\curve\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\curve\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in .\curve\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\curve\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
from sqlalchemy import create_engine,text

In [5]:
engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

NameError: name 'create_engine' is not defined

In [6]:
vacancy_loss_sql = text("""
SELECT
    SUM(COALESCE(c.total_amount, 0)) AS vacancy_loss
FROM eq_ls_property_unit pu
LEFT JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
WHERE pu.booked_at IS NULL
  AND pu.unit_excluded = 0;
""")

with engine.connect() as conn:
    vacancy_loss = conn.execute(vacancy_loss_sql).scalar()

print("1️⃣ Vacancy Revenue Loss:", vacancy_loss)

1️⃣ Vacancy Revenue Loss: 23602678.00

In [7]:
vacancy_by_property_sql = text("""
SELECT
    pu.PROPERTY_ID,
    SUM(COALESCE(c.total_amount, 0)) AS vacancy_loss
FROM eq_ls_property_unit pu
LEFT JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
WHERE pu.booked_at IS NULL
  AND pu.unit_excluded = 0
GROUP BY pu.PROPERTY_ID
ORDER BY vacancy_loss DESC;
""")

with engine.connect() as conn:
    vacancy_by_property = conn.execute(vacancy_by_property_sql).mappings().all()

print("\n2️⃣ Properties with highest vacancy loss:")
for row in vacancy_by_property:
    print(row)

2️⃣ Properties with highest vacancy loss:
{'PROPERTY_ID': 32, 'vacancy_loss': Decimal('9000000.00')}
{'PROPERTY_ID': 139, 'vacancy_loss': Decimal('2820000.00')}
{'PROPERTY_ID': 78, 'vacancy_loss': Decimal('2250000.00')}
{'PROPERTY_ID': 77, 'vacancy_loss': Decimal('1536000.00')}
{'PROPERTY_ID': 102, 'vacancy_loss': Decimal('800000.00')}
{'PROPERTY_ID': 16, 'vacancy_loss': Decimal('600000.00')}
{'PROPERTY_ID': 90, 'vacancy_loss': Decimal('540000.00')}
{'PROPERTY_ID': 59, 'vacancy_loss': Decimal('485200.00')}
{'PROPERTY_ID': 138, 'vacancy_loss': Decimal('477000.00')}
{'PROPERTY_ID': 129, 'vacancy_loss': Decimal('455000.00')}
{'PROPERTY_ID': 101, 'vacancy_loss': Decimal('365000.00')}
{'PROPERTY_ID': 118, 'vacancy_loss': Decimal('362000.00')}
{'PROPERTY_ID': 97, 'vacancy_loss': Decimal('320000.00')}
{'PROPERTY_ID': 157, 'vacancy_loss': Decimal('309000.00')}
{'PROPERTY_ID': 201, 'vacancy_loss': Decimal('225000.00')}
{'PROPERTY_ID': 87, 'vacancy_loss': Decimal('190000.00')}
{'PROPERTY_ID': 158, 'vacancy_loss': Decimal('185000.00')}
{'PROPERTY_ID': 131, 'vacancy_loss': Decimal('180000.00')}
{'PROPERTY_ID': 180, 'vacancy_loss': Decimal('161000.00')}
{'PROPERTY_ID': 142, 'vacancy_loss': Decimal('151200.00')}
{'PROPERTY_ID': 103, 'vacancy_loss': Decimal('150200.00')}
{'PROPERTY_ID': 160, 'vacancy_loss': Decimal('125000.00')}
{'PROPERTY_ID': 121, 'vacancy_loss': Decimal('120000.00')}
{'PROPERTY_ID': 182, 'vacancy_loss': Decimal('106000.00')}
{'PROPERTY_ID': 156, 'vacancy_loss': Decimal('100344.00')}
{'PROPERTY_ID': 71, 'vacancy_loss': Decimal('90000.00')}
{'PROPERTY_ID': 170, 'vacancy_loss': Decimal('73000.00')}
{'PROPERTY_ID': 29, 'vacancy_loss': Decimal('71100.00')}
{'PROPERTY_ID': 86, 'vacancy_loss': Decimal('70000.00')}
{'PROPERTY_ID': 89, 'vacancy_loss': Decimal('67500.00')}
{'PROPERTY_ID': 53, 'vacancy_loss': Decimal('61000.00')}
{'PROPERTY_ID': 9, 'vacancy_loss': Decimal('60000.00')}
{'PROPERTY_ID': 93, 'vacancy_loss': Decimal('60000.00')}
{'PROPERTY_ID': 24, 'vacancy_loss': Decimal('51000.00')}
{'PROPERTY_ID': 149, 'vacancy_loss': Decimal('51000.00')}
{'PROPERTY_ID': 11, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 120, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 135, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 132, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 136, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 171, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 2, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 193, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 96, 'vacancy_loss': Decimal('46000.00')}
{'PROPERTY_ID': 128, 'vacancy_loss': Decimal('46000.00')}
{'PROPERTY_ID': 153, 'vacancy_loss': Decimal('40000.00')}
{'PROPERTY_ID': 147, 'vacancy_loss': Decimal('34200.00')}
{'PROPERTY_ID': 150, 'vacancy_loss': Decimal('30000.00')}
{'PROPERTY_ID': 154, 'vacancy_loss': Decimal('30000.00')}
{'PROPERTY_ID': 30, 'vacancy_loss': Decimal('29200.00')}
{'PROPERTY_ID': 65, 'vacancy_loss': Decimal('25000.00')}
{'PROPERTY_ID': 74, 'vacancy_loss': Decimal('21000.00')}
{'PROPERTY_ID': 184, 'vacancy_loss': Decimal('20001.00')}
{'PROPERTY_ID': 46, 'vacancy_loss': Decimal('17400.00')}
{'PROPERTY_ID': 52, 'vacancy_loss': Decimal('16200.00')}
{'PROPERTY_ID': 27, 'vacancy_loss': Decimal('15000.00')}
{'PROPERTY_ID': 39, 'vacancy_loss': Decimal('14400.00')}
{'PROPERTY_ID': 56, 'vacancy_loss': Decimal('10200.00')}
{'PROPERTY_ID': 31, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 67, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 123, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 188, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 173, 'vacancy_loss': Decimal('9000.00')}
{'PROPERTY_ID': 14, 'vacancy_loss': Decimal('7300.00')}
{'PROPERTY_ID': 82, 'vacancy_loss': Decimal('6000.00')}
{'PROPERTY_ID': 50, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 23, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 92, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 108, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 183, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 203, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 211, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 18, 'vacancy_loss': Decimal('4000.00')}
{'PROPERTY_ID': 37, 'vacancy_loss': Decimal('4000.00')}
{'PROPERTY_ID': 85, 'vacancy_loss': Decimal('3500.00')}
{'PROPERTY_ID': 70, 'vacancy_loss': Decimal('3333.00')}
{'PROPERTY_ID': 73, 'vacancy_loss': Decimal('3200.00')}
{'PROPERTY_ID': 63, 'vacancy_loss': Decimal('3100.00')}
{'PROPERTY_ID': 159, 'vacancy_loss': Decimal('2500.00')}
{'PROPERTY_ID': 54, 'vacancy_loss': Decimal('2200.00')}
{'PROPERTY_ID': 3, 'vacancy_loss': Decimal('2000.00')}
{'PROPERTY_ID': 28, 'vacancy_loss': Decimal('1700.00')}
{'PROPERTY_ID': 174, 'vacancy_loss': Decimal('1500.00')}
{'PROPERTY_ID': 210, 'vacancy_loss': Decimal('1500.00')}
{'PROPERTY_ID': 49, 'vacancy_loss': Decimal('1300.00')}
{'PROPERTY_ID': 48, 'vacancy_loss': Decimal('1200.00')}
{'PROPERTY_ID': 58, 'vacancy_loss': Decimal('1200.00')}
{'PROPERTY_ID': 192, 'vacancy_loss': Decimal('1200.00')}
{'PROPERTY_ID': 98, 'vacancy_loss': Decimal('1100.00')}
{'PROPERTY_ID': 26, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 80, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 144, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 143, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 68, 'vacancy_loss': Decimal('500.00')}
{'PROPERTY_ID': 6, 'vacancy_loss': Decimal('100.00')}
{'PROPERTY_ID': 75, 'vacancy_loss': Decimal('100.00')}
{'PROPERTY_ID': 44, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 51, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 66, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 72, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 76, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 109, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 204, 'vacancy_loss': Decimal('0.00')}

In [8]:
delayed_collection_sql = text("""
SELECT
    SUM(total_amount - COALESCE(APPROVED_AMOUNT, 0)) AS delayed_collection_loss
FROM eq_ls_property_unit_charges
WHERE CHARGE_CODE = 1
  AND created_at < CURRENT_DATE
  AND deleted_at IS NULL
  AND (APPROVED_AMOUNT IS NULL OR APPROVED_AMOUNT < total_amount);
""")

with engine.connect() as conn:
    delayed_loss = conn.execute(delayed_collection_sql).scalar()

print("\n3️⃣ Delayed Collection Loss:", delayed_loss)

3️⃣ Delayed Collection Loss: 3762366.00

In [9]:
unpaid_moveout_sql = text("""
SELECT
    pu.ID AS unit_id,
    pu.PROPERTY_ID,
    SUM(c.total_amount - COALESCE(c.APPROVED_AMOUNT, 0)) AS unpaid_due
FROM eq_ls_property_unit pu
JOIN eq_ls_property_unit_charges c
    ON pu.ID = c.PROPERTY_UNIT
WHERE pu.booked_at IS NULL
  AND c.deleted_at IS NULL
GROUP BY pu.ID, pu.PROPERTY_ID
HAVING unpaid_due > 0
ORDER BY unpaid_due DESC;
""")

with engine.connect() as conn:
    unpaid_units = conn.execute(unpaid_moveout_sql).mappings().all()

print("\n4️⃣ Units with unpaid dues at move-out:")
for row in unpaid_units:
    print(row)

4️⃣ Units with unpaid dues at move-out:
{'unit_id': 25, 'PROPERTY_ID': 16, 'unpaid_due': Decimal('510000.00')}
{'unit_id': 847, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('230000.00')}
{'unit_id': 1255, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1256, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1257, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1258, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1259, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1260, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1261, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1262, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 26, 'PROPERTY_ID': 16, 'unpaid_due': Decimal('50000.00')}
{'unit_id': 875, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('50000.00')}
{'unit_id': 382, 'PROPERTY_ID': 86, 'unpaid_due': Decimal('45000.00')}
{'unit_id': 941, 'PROPERTY_ID': 87, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 977, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 980, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 981, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 982, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 983, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 984, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 985, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 986, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 987, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 874, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('30000.00')}
{'unit_id': 989, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 990, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 991, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 992, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 993, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 994, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 995, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 996, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 998, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 999, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1000, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1001, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1002, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1003, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1004, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1005, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1006, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1007, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1008, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1009, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1010, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1011, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1012, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1013, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1014, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1015, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1016, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1017, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1018, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1019, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1020, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1021, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1022, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1023, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1024, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1025, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1026, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1027, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 266, 'PROPERTY_ID': 74, 'unpaid_due': Decimal('20100.00')}
{'unit_id': 872, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1123, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1125, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1127, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1130, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1131, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1488, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('15000.00')}
{'unit_id': 1489, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('15000.00')}
{'unit_id': 1490, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('15000.00')}
{'unit_id': 319, 'PROPERTY_ID': 46, 'unpaid_due': Decimal('14500.00')}
{'unit_id': 1228, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('13500.00')}
{'unit_id': 1585, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1586, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1587, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1588, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1589, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 169, 'PROPERTY_ID': 29, 'unpaid_due': Decimal('12000.00')}
{'unit_id': 1482, 'PROPERTY_ID': 2, 'unpaid_due': Decimal('11000.00')}
{'unit_id': 689, 'PROPERTY_ID': 103, 'unpaid_due': Decimal('10500.00')}
{'unit_id': 24, 'PROPERTY_ID': 16, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 862, 'PROPERTY_ID': 120, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1108, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1109, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1110, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1196, 'PROPERTY_ID': 156, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1280, 'PROPERTY_ID': 142, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 932, 'PROPERTY_ID': 123, 'unpaid_due': Decimal('9000.00')}
{'unit_id': 51, 'PROPERTY_ID': 11, 'unpaid_due': Decimal('8500.00')}
{'unit_id': 1223, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('8250.00')}
{'unit_id': 1225, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('8250.00')}
{'unit_id': 1226, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('8250.00')}
{'unit_id': 845, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('8000.00')}
{'unit_id': 846, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('8000.00')}
{'unit_id': 692, 'PROPERTY_ID': 104, 'unpaid_due': Decimal('7500.00')}
{'unit_id': 374, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('7400.00')}
{'unit_id': 900, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('7000.00')}
{'unit_id': 901, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('7000.00')}
{'unit_id': 1331, 'PROPERTY_ID': 149, 'unpaid_due': Decimal('7000.00')}
{'unit_id': 146, 'PROPERTY_ID': 37, 'unpaid_due': Decimal('6900.00')}
{'unit_id': 696, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 697, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 698, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 699, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 700, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 701, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 702, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 703, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 704, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 705, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 706, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 707, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 708, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 709, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 710, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 711, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 712, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 713, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 714, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 715, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 716, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 717, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 718, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 719, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 720, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 721, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 722, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 723, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 724, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 725, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 726, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 727, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 728, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 729, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 730, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 731, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 732, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 733, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 734, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 735, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 736, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 737, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 738, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 739, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 740, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 818, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 1229, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('5400.00')}
{'unit_id': 47, 'PROPERTY_ID': 20, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 160, 'PROPERTY_ID': 53, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 186, 'PROPERTY_ID': 67, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 853, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 876, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 882, 'PROPERTY_ID': 128, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 935, 'PROPERTY_ID': 135, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 1310, 'PROPERTY_ID': 142, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 1377, 'PROPERTY_ID': 156, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 181, 'PROPERTY_ID': 65, 'unpaid_due': Decimal('4500.00')}
{'unit_id': 176, 'PROPERTY_ID': 58, 'unpaid_due': Decimal('4200.00')}
{'unit_id': 316, 'PROPERTY_ID': 28, 'unpaid_due': Decimal('4200.00')}
{'unit_id': 263, 'PROPERTY_ID': 70, 'unpaid_due': Decimal('4100.00')}
{'unit_id': 156, 'PROPERTY_ID': 50, 'unpaid_due': Decimal('4000.00')}
{'unit_id': 369, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3900.00')}
{'unit_id': 370, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3900.00')}
{'unit_id': 178, 'PROPERTY_ID': 63, 'unpaid_due': Decimal('3700.00')}
{'unit_id': 244, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3600.00')}
{'unit_id': 272, 'PROPERTY_ID': 71, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 273, 'PROPERTY_ID': 71, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1183, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1184, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1185, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1186, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1187, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1190, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 371, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3300.00')}
{'unit_id': 159, 'PROPERTY_ID': 53, 'unpaid_due': Decimal('3000.00')}
{'unit_id': 207, 'PROPERTY_ID': 3, 'unpaid_due': Decimal('3000.00')}
{'unit_id': 275, 'PROPERTY_ID': 56, 'unpaid_due': Decimal('2700.00')}
{'unit_id': 1171, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1172, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1173, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1174, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1175, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1176, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1386, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 405, 'PROPERTY_ID': 89, 'unpaid_due': Decimal('2450.00')}
{'unit_id': 1230, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1265, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1267, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1268, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1269, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1270, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1273, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1274, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1321, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1322, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1323, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1324, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1325, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1326, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1327, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1328, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1311, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1312, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1313, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1314, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1315, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1318, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1319, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 848, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('2111.00')}
{'unit_id': 1159, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1160, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1161, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1162, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1163, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1164, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1165, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1166, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 234, 'PROPERTY_ID': 73, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 866, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 881, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1089, 'PROPERTY_ID': 149, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1091, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1092, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1093, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1094, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1095, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1096, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1097, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1098, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1099, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1277, 'PROPERTY_ID': 142, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1428, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 179, 'PROPERTY_ID': 63, 'unpaid_due': Decimal('1850.00')}
{'unit_id': 1241, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1243, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1245, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1246, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1247, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1248, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1249, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1250, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1251, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1252, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1417, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('1730.00')}
{'unit_id': 233, 'PROPERTY_ID': 73, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1135, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1136, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1137, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1138, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1139, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1140, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1141, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1142, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1538, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 265, 'PROPERTY_ID': 74, 'unpaid_due': Decimal('1400.00')}
{'unit_id': 1400, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('1400.00')}
{'unit_id': 190, 'PROPERTY_ID': 46, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1352, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1353, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1354, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1080, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1212, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1213, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1214, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1215, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1216, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1217, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1218, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1219, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1356, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1357, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1358, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1359, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1360, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1361, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1362, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}

In [ ]:
from sqlalchemy import text

deposit_writeoff_sql = text("""
SELECT
    SUM(total_amount - COALESCE(APPROVED_AMOUNT, 0)) AS deposit_written_off
FROM eq_ls_property_unit_charges
WHERE CHARGE_CODE = 2
  AND deleted_at IS NULL
  AND (APPROVED_AMOUNT IS NULL OR APPROVED_AMOUNT < total_amount);
""")

with engine.connect() as conn:
    deposit_loss = conn.execute(deposit_writeoff_sql).scalar()

print("5️⃣ Deposit Written-off Amount:", deposit_loss)

5️⃣ Deposit Written-off Amount: 3133545.00

In [11]:
import pandas as pd
query = """
SELECT
    PROPERTY_UNIT AS unit_id,
    SUM(total_amount - COALESCE(APPROVED_AMOUNT, 0)) AS delayed_loss
FROM eq_ls_property_unit_charges
WHERE CHARGE_CODE = 1
  AND deleted_at IS NULL
  AND APPROVED_AMOUNT IS NOT NULL
  AND APPROVED_AMOUNT < total_amount
GROUP BY PROPERTY_UNIT;
"""
df_delayed = pd.read_sql(query, engine)
df_delayed

     unit_id  delayed_loss
0         48        5000.0
1         49        5000.0
2         51        5000.0
3         50        5000.0
4         72         200.0
..       ...           ...
576     1609         500.0
577     1610         500.0
578     1611         500.0
579     1612         500.0
580     1639        5000.0

[581 rows x 2 columns]

In [1]:
df_delayed['delayed_loss'].sum()

NameError: name 'df_delayed' is not defined

In [13]:
query = """
SELECT
    pu.ID AS unit_id,
    pu.PROPERTY_ID,
    COALESCE(c.total_amount, 0) AS renewal_gap_loss
FROM eq_ls_property_unit pu
LEFT JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
WHERE pu.booked_at IS NULL
  AND pu.unit_excluded = 0
  AND pu.STATUS = 1;
"""
df_renewal_gap = pd.read_sql(query, engine)
df_renewal_gap

     unit_id  PROPERTY_ID  renewal_gap_loss
0        172           52            1000.0
1        175           58               0.0
2        177           56            5000.0
3        179           63             100.0
4        181           65            5000.0
..       ...          ...               ...
442     1589          201           45000.0
443     1613          203            5000.0
444     1631          204               0.0
445     1647          210            1500.0
446     1648          211            5000.0

[447 rows x 3 columns]

In [ ]:
df_renewal_gap['renewal_gap_loss'].sum()

np.float64(11706777.0)

# Vacancy % = Vacant Units / Total Units × 100

In [15]:
query = """
SELECT
    COUNT(*) AS total_units,
    SUM(CASE WHEN booked_at IS NULL THEN 1 ELSE 0 END) AS vacant_units,
    ROUND(
        SUM(CASE WHEN booked_at IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS vacancy_percentage
FROM eq_ls_property_unit
WHERE unit_excluded = 0;
"""
df_vacancy = pd.read_sql(query, engine)
df_vacancy

   total_units  vacant_units  vacancy_percentage
0         1572         607.0               38.61

In [16]:
query = """
WITH market_rent AS (
    SELECT
        pu.UNIT_TYPE,
        AVG(c.total_amount) AS avg_market_rent
    FROM eq_ls_property_unit pu
    JOIN eq_ls_property_unit_charges c
        ON pu.ID = c.PROPERTY_UNIT
    WHERE c.CHARGE_CODE = 1
      AND c.deleted_at IS NULL
    GROUP BY pu.UNIT_TYPE
)
SELECT
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    put.NAME AS unit_type_name,
    c.total_amount AS actual_rent,
    mr.avg_market_rent,
    (mr.avg_market_rent - c.total_amount) AS rent_leakage
FROM eq_ls_property_unit pu
JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
JOIN market_rent mr
    ON pu.UNIT_TYPE = mr.UNIT_TYPE
JOIN eq_ls_property_unit_type put
    ON pu.UNIT_TYPE = put.ID
WHERE c.total_amount < mr.avg_market_rent;
"""
df_below_market = pd.read_sql(query, engine)
df_below_market

,unit_id,UNIT_TYPE,unit_type_name,actual_rent,avg_market_rent,rent_leakage
0,14,1,"1-Bedroom, 1-Baths",2000.0,25165.955399,23165.955399
1,19,1,"1-Bedroom, 1-Baths",2300.0,25165.955399,22865.955399
2,20,1,"1-Bedroom, 1-Baths",5000.0,25165.955399,20165.955399
3,21,1,"1-Bedroom, 1-Baths",5000.0,25165.955399,20165.955399
4,23,1,"1-Bedroom, 1-Baths",3000.0,25165.955399,22165.955399
...,...,...,...,...,...,...
849,1526,40,2BHK Apartment,10000.0,70760.000000,60760.000000
850,1528,40,2BHK Apartment,7000.0,70760.000000,63760.000000
851,1535,40,2BHK Apartment,5000.0,70760.000000,65760.000000
852,1536,40,2BHK Apartment,5000.0,70760.000000,65760.000000
853,1537,40,2BHK Apartment,5000.0,70760.000000,65760.000000

In [17]:
df_below_market['rent_leakage'].sum()

np.float64(23085191.129031003)

# below market in certain properties

In [ ]:
from sqlalchemy import text
import pandas as pd

# Updated SQL query using avg_market_rent
overpricing_sql = text("""
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    CAST(pu.asking_rent AS DECIMAL(10,2)) AS asking_rent,
    CAST(m.avg_market_rent AS DECIMAL(10,2)) AS avg_market_rent,   -- replaced with correct column
    DATEDIFF(CURDATE(), pu.last_vacant_date) AS vacant_days,
    (DATEDIFF(CURDATE(), pu.last_vacant_date) / 30) * CAST(m.avg_market_rent AS DECIMAL(10,2)) AS blocked_revenue
FROM eq_ls_property_unit pu
JOIN market_rent_reference m
    ON m.UNIT_TYPE = pu.UNIT_TYPE
WHERE pu.occupancy_status = 'VACANT'
  AND CAST(pu.asking_rent AS DECIMAL(10,2)) > CAST(m.avg_market_rent AS DECIMAL(10,2))
LIMIT 10
""")

# Execute query with pandas
df_overpricing = pd.read_sql(overpricing_sql, engine)

# Preview results
df_overpricing.head()

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'equal_react_curve.market_rent_reference' doesn't exist")
[SQL:
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    CAST(pu.asking_rent AS DECIMAL(10,2)) AS asking_rent,
    CAST(m.avg_market_rent AS DECIMAL(10,2)) AS avg_market_rent,   -- replaced with correct column
    DATEDIFF(CURDATE(), pu.last_vacant_date) AS vacant_days,
    (DATEDIFF(CURDATE(), pu.last_vacant_date) / 30) * CAST(m.avg_market_rent AS DECIMAL(10,2)) AS blocked_revenue
FROM eq_ls_property_unit pu
JOIN market_rent_reference m
    ON m.UNIT_TYPE = pu.UNIT_TYPE
WHERE pu.occupancy_status = 'VACANT'
  AND CAST(pu.asking_rent AS DECIMAL(10,2)) > CAST(m.avg_market_rent AS DECIMAL(10,2))
LIMIT 10
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [18]:
query = (
    "SELECT * "
    "FROM ( "
    "    SELECT "
    "        pu.PROPERTY_ID, "
    "        pu.ID AS unit_id, "
    "        pu.UNIT_TYPE, "
    "        AVG(c.total_amount) AS actual_rent, "
    "        m.market_rent, "
    "        (m.market_rent - AVG(c.total_amount)) AS monthly_leakage "
    "    FROM eq_ls_property_unit_charges c "
    "    JOIN eq_ls_property_unit pu ON pu.ID = c.PROPERTY_UNIT "
    "    JOIN market_rent_reference m ON m.unit_type = pu.UNIT_TYPE "
    "    WHERE c.CHARGE_CODE = 1 AND c.deleted_at IS NULL "
    "    GROUP BY pu.PROPERTY_ID, pu.ID, pu.UNIT_TYPE, m.market_rent "
    ") AS t "
    "WHERE actual_rent < market_rent "
    "ORDER BY monthly_leakage DESC;"
)

In [19]:

df_below_market.head()

,unit_id,UNIT_TYPE,unit_type_name,actual_rent,avg_market_rent,rent_leakage
0,14,1,"1-Bedroom, 1-Baths",2000.0,25165.955399,23165.955399
1,19,1,"1-Bedroom, 1-Baths",2300.0,25165.955399,22865.955399
2,20,1,"1-Bedroom, 1-Baths",5000.0,25165.955399,20165.955399
3,21,1,"1-Bedroom, 1-Baths",5000.0,25165.955399,20165.955399
4,23,1,"1-Bedroom, 1-Baths",3000.0,25165.955399,22165.955399

# over pricing

In [ ]:
from sqlalchemy import text
import pandas as pd

# Updated SQL query with two reference rent columns
overpricing_sql = text("""
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    CAST(pu.asking_rent AS DECIMAL(10,2)) AS asking_rent,
    CAST(m.benchmark_rent AS DECIMAL(10,2)) AS benchmark_rent,    -- first reference
    CAST(m.alternative_rent AS DECIMAL(10,2)) AS alternative_rent, -- second reference
    DATEDIFF(CURDATE(), pu.last_vacant_date) AS vacant_days,
    -- calculation using benchmark_rent; can switch to alternative_rent if needed
    (DATEDIFF(CURDATE(), pu.last_vacant_date) / 30) * CAST(m.benchmark_rent AS DECIMAL(10,2)) AS blocked_revenue
FROM eq_ls_property_unit pu
JOIN market_rent_reference m
    ON m.unit_type = pu.UNIT_TYPE
WHERE pu.occupancy_status = 'VACANT'
  AND CAST(pu.asking_rent AS DECIMAL(10,2)) > CAST(m.benchmark_rent AS DECIMAL(10,2))
LIMIT 10
""")

# Execute query with pandas
df_overpricing = pd.read_sql(overpricing_sql, engine)

# Preview results
df_overpricing.head()

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'equal_react_curve.market_rent_reference' doesn't exist")
[SQL:
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    CAST(pu.asking_rent AS DECIMAL(10,2)) AS asking_rent,
    CAST(m.benchmark_rent AS DECIMAL(10,2)) AS benchmark_rent,    -- first reference
    CAST(m.alternative_rent AS DECIMAL(10,2)) AS alternative_rent, -- second reference
    DATEDIFF(CURDATE(), pu.last_vacant_date) AS vacant_days,
    -- calculation using benchmark_rent; can switch to alternative_rent if needed
    (DATEDIFF(CURDATE(), pu.last_vacant_date) / 30) * CAST(m.benchmark_rent AS DECIMAL(10,2)) AS blocked_revenue
FROM eq_ls_property_unit pu
JOIN market_rent_reference m
    ON m.unit_type = pu.UNIT_TYPE
WHERE pu.occupancy_status = 'VACANT'
  AND CAST(pu.asking_rent AS DECIMAL(10,2)) > CAST(m.benchmark_rent AS DECIMAL(10,2))
LIMIT 10
]
(Background on this error at: https://sqlalche.me/e/20/f405)

# Slow Turnaround After Move-Out

# total_hidden_leakage

In [ ]:
print(query)
df = pd.read_sql(query, engine)

SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    AVG(c.total_amount) AS actual_rent,
    m.market_rent,
    (m.market_rent - AVG(c.total_amount)) AS monthly_leakage
FROM eq_ls_property_unit_charges c
JOIN eq_ls_property_unit pu
    ON pu.ID = c.PROPERTY_UNIT
JOIN market_rent_reference m
    ON m.unit_type = pu.UNIT_TYPE
WHERE c.CHARGE_CODE = 1
  AND c.deleted_at IS NULL
GROUP BY
    pu.PROPERTY_ID,
    pu.ID,
    pu.UNIT_TYPE,
    m.market_rent
HAVING AVG(c.total_amount) < m.market_rent
ORDER BY monthly_leakage DESC
LIMIT 10;

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'equal_react_curve.market_rent_reference' doesn't exist")
[SQL:
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    AVG(c.total_amount) AS actual_rent,
    m.market_rent,
    (m.market_rent - AVG(c.total_amount)) AS monthly_leakage
FROM eq_ls_property_unit_charges c
JOIN eq_ls_property_unit pu
    ON pu.ID = c.PROPERTY_UNIT
JOIN market_rent_reference m
    ON m.unit_type = pu.UNIT_TYPE
WHERE c.CHARGE_CODE = 1
  AND c.deleted_at IS NULL
GROUP BY
    pu.PROPERTY_ID,
    pu.ID,
    pu.UNIT_TYPE,
    m.market_rent
HAVING AVG(c.total_amount) < m.market_rent
ORDER BY monthly_leakage DESC
LIMIT 10;
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [24]:
query = """
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    AVG(c.total_amount) AS actual_rent,
    m.market_rent,
    (m.market_rent - AVG(c.total_amount)) AS monthly_leakage
FROM eq_ls_property_unit_charges c
JOIN eq_ls_property_unit pu
    ON pu.ID = c.PROPERTY_UNIT
JOIN market_rent_reference m
    ON m.unit_type = pu.UNIT_TYPE
WHERE c.CHARGE_CODE = 1
  AND c.deleted_at IS NULL
GROUP BY
    pu.PROPERTY_ID,
    pu.ID,
    pu.UNIT_TYPE,
    m.market_rent
HAVING AVG(c.total_amount) < m.market_rent
ORDER BY monthly_leakage DESC
LIMIT 10;
"""

In [23]:
df_below_market.columns

Index(['unit_id', 'UNIT_TYPE', 'unit_type_name', 'actual_rent',
       'avg_market_rent', 'monthly_leakage'],
      dtype='object')

In [21]:
df_below_market = df_below_market.rename(
    columns={'rent_leakage': 'monthly_leakage'}
)

In [42]:
from sqlalchemy import text
import pandas as pd

# Legal / Documentation Blocked Revenue Query
legal_block_sql = text("""
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.block_reason,
    DATEDIFF(CURDATE(), pu.block_start_date) AS blocked_days,
    AVG(c.total_amount) AS expected_rent,
    (DATEDIFF(CURDATE(), pu.block_start_date) / 30) * AVG(c.total_amount) AS blocked_revenue
FROM eq_ls_property_unit pu
JOIN eq_ls_property_unit_charges c
    ON c.UNIT_ID = pu.ID
WHERE pu.leaseable = 0
  AND pu.block_reason IN ('LEGAL', 'DOCUMENTATION')
  AND c.CHARGE_CODE = 1
GROUP BY pu.PROPERTY_ID, pu.ID, pu.block_reason, pu.block_start_date
ORDER BY blocked_revenue DESC
LIMIT 50
""")

# Execute query with pandas
df_legal_block = pd.read_sql(legal_block_sql, engine)

# Preview results
print("⚖️ Legal / Documentation Blocked Revenue")
print(df_legal_block.head())

KeyboardInterrupt

In [46]:
turnaround_sql = text("""
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.move_out_date,
    DATEDIFF(CURDATE(), pu.move_out_date) AS idle_days,
    AVG(c.total_amount) AS expected_rent,
    (DATEDIFF(CURDATE(), pu.move_out_date) / 30) * AVG(c.total_amount) AS turnaround_loss
FROM eq_ls_property_unit pu
JOIN eq_ls_property_unit_charges c
    ON c.PROPERTY_UNIT = pu.ID
WHERE pu.move_out_date IS NOT NULL
  AND pu.occupancy_status = 'VACANT'
  AND c.CHARGE_CODE = 1
GROUP BY pu.PROPERTY_ID, pu.ID, pu.move_out_date
ORDER BY turnaround_loss DESC;
""")

df_turnaround = pd.read_sql(query, engine)
print("⏳ Turnaround Leakage")
print(df_turnaround.head())

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'equal_react_curve.market_rent_reference' doesn't exist")
[SQL:
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    AVG(c.total_amount) AS actual_rent,
    m.market_rent,
    (m.market_rent - AVG(c.total_amount)) AS monthly_leakage
FROM eq_ls_property_unit_charges c
JOIN eq_ls_property_unit pu
    ON pu.ID = c.PROPERTY_UNIT
JOIN market_rent_reference m
    ON m.unit_type = pu.UNIT_TYPE
WHERE c.CHARGE_CODE = 1
  AND c.deleted_at IS NULL
GROUP BY
    pu.PROPERTY_ID,
    pu.ID,
    pu.UNIT_TYPE,
    m.market_rent
HAVING AVG(c.total_amount) < m.market_rent
ORDER BY monthly_leakage DESC
LIMIT 10;
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [50]:
from sqlalchemy import text

turnaround_sql = text("""
SELECT
    pu.PROPERTY_ID,
    pu.ID AS unit_id,
    pu.move_out_date,
    DATEDIFF(CURDATE(), pu.move_out_date) AS idle_days,
    AVG(c.total_amount) AS expected_rent,
    ROUND((DATEDIFF(CURDATE(), pu.move_out_date) / 30) * AVG(c.total_amount), 2) AS turnaround_loss
FROM eq_ls_property_unit pu
JOIN eq_ls_property_unit_charges c
    ON c.PROPERTY_UNIT = pu.ID
WHERE pu.move_out_date IS NOT NULL
  AND pu.occupancy_status = 'VACANT'
  AND c.CHARGE_CODE = 1
GROUP BY pu.PROPERTY_ID, pu.ID, pu.move_out_date
ORDER BY ROUND((DATEDIFF(CURDATE(), pu.move_out_date) / 30) * AVG(c.total_amount), 2) DESC;
""")

df_turnaround = pd.read_sql(turnaround_sql, engine)
print("⏳ Turnaround Leakage")
print(df_turnaround.head())

KeyboardInterrupt

In [ ]:
GROUP BY pu.PROPERTY_ID, pu.ID, pu.block_reason, pu.block_start_date
ORDER BY blocked_revenue DESC
LIMIT 50

# a. Renewal Rate

In [52]:
query = """
SELECT
    PROPERTY_ID,
    COUNT(*) AS total_leases,
    SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) AS renewed_count,
    ROUND(SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS renewal_rate
FROM leases
WHERE lease_end_date BETWEEN '2025-01-01' AND '2025-12-31'
GROUP BY PROPERTY_ID
ORDER BY renewal_rate ASC;
"""

# Renewal by Rent Bands

In [53]:
query = """
SELECT
    CASE
        WHEN monthly_rent BETWEEN 0 AND 10000 THEN 'Band 1'
        WHEN monthly_rent BETWEEN 10001 AND 20000 THEN 'Band 2'
        WHEN monthly_rent > 20000 THEN 'Band 3'
    END AS rent_band,
    COUNT(*) AS total_leases,
    SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) AS renewed_count,
    ROUND(SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS renewal_rate
FROM leases
GROUP BY rent_band
ORDER BY rent_band;
"""

In [ ]:
# Renewal vs Rent Increase %

In [54]:
query = """
SELECT
    CASE
        WHEN rent_increase_pct BETWEEN 0 AND 5 THEN '0-5%'
        WHEN rent_increase_pct BETWEEN 5.01 AND 10 THEN '5-10%'
        ELSE '>10%'
    END AS rent_increase_band,
    COUNT(*) AS total_leases,
    SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) AS renewed_count,
    ROUND(SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS renewal_rate
FROM leases
GROUP BY rent_increase_band
ORDER BY rent_increase_band;
"""

In [ ]:
# Renewal vs Late Payments

In [55]:
query = """
SELECT
    CASE WHEN late_payment_count > 2 THEN 'Late Payers' ELSE 'On-time Payers' END AS payment_type,
    COUNT(*) AS total_leases,
    SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) AS renewed_count,
    ROUND(SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS renewal_rate
FROM leases
GROUP BY payment_type;
"""

In [ ]:
 # Renewal vs Tenant Tenure

In [56]:
query = """
SELECT
    CASE
        WHEN tenure_months < 12 THEN '<1 Year'
        WHEN tenure_months BETWEEN 12 AND 24 THEN '1-2 Years'
        ELSE '>2 Years'
    END AS tenure_band,
    COUNT(*) AS total_leases,
    SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) AS renewed_count,
    ROUND(SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS renewal_rate
FROM leases
GROUP BY tenure_band
ORDER BY tenure_band;
"""

In [ ]:
# Renewal vs Tenant Type (Corporate vs Individual

In [84]:
query = """
SELECT
    tenant_type,  -- 'Corporate' or 'Individual'
    COUNT(*) AS total_leases,
    SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) AS renewed_count,
    ROUND(SUM(CASE WHEN renewal_status = 'RENEWED' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS renewal_rate
FROM leases
GROUP BY tenant_type
ORDER BY renewal_rate ASC;
"""

In [70]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime, timedelta

In [78]:
engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

In [86]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime, timedelta

# -------------------------------
# 1️⃣ Connect to MySQL
# -------------------------------
engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

# -------------------------------
# 2️⃣ Load REAL lease data
# -------------------------------
df = pd.read_sql("""
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    occupancy_status,
    move_in_date,
    move_out_date,
    lease_end_date,
    monthly_rent
FROM eq_ls_property_unit
""", engine)

# -------------------------------
# 3️⃣ Renewal logic (NO renewal table needed)
# -------------------------------
df['renewal_status'] = np.where(
    df['move_out_date'].isna(),
    'RENEWED',
    'TERMINATED'
)

# -------------------------------
# 4️⃣ Tenure calculation
# -------------------------------
df['move_in_date'] = pd.to_datetime(df['move_in_date'])
df['tenure_months'] = ((datetime.today() - df['move_in_date']).dt.days / 30).astype(int)

df['tenure_band'] = pd.cut(
    df['tenure_months'],
    bins=[0, 12, 24, 1000],
    labels=['<1 Year', '1–2 Years', '>2 Years']
)

# -------------------------------
# 5️⃣ Rent bands
# -------------------------------
df['rent_band'] = pd.cut(
    df['monthly_rent'],
    bins=[0, 10000, 20000, 1e9],
    labels=['0–10k', '10–20k', '>20k']
)

# -------------------------------
# 6️⃣ Renewal KPIs
# -------------------------------
renewal_by_property = (
    df.groupby('PROPERTY_ID')['renewal_status']
    .apply(lambda x: (x == 'RENEWED').mean() * 100)
    .round(2)
    .sort_values()
)

print("🔁 Renewal Rate by Property (%)")
print(renewal_by_property.head())

# -------------------------------
# 7️⃣ Risk: expiring leases
# -------------------------------
today = datetime.today()

risk_30 = df[df['lease_end_date'].between(today, today + timedelta(days=30))]
risk_60 = df[df['lease_end_date'].between(today, today + timedelta(days=60))]
risk_90 = df[df['lease_end_date'].between(today, today + timedelta(days=90))]

print("\n⚠️ Lease Expiry Risk")
print("Next 30 days:", len(risk_30))
print("Next 60 days:", len(risk_60))
print("Next 90 days:", len(risk_90))

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'occupancy_status' in 'field list'")
[SQL:
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    occupancy_status,
    move_in_date,
    move_out_date,
    lease_end_date,
    monthly_rent
FROM eq_ls_property_unit
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [87]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

cols = pd.read_sql("DESCRIBE eq_ls_property_unit", engine)
print(cols[['Field', 'Type']])

                                         Field             Type
0                                           ID  bigint unsigned
1                                   company_id  bigint unsigned
2                                    branch_id  bigint unsigned
3                                         CODE      varchar(50)
4                                  PROPERTY_ID  bigint unsigned
5                                     FLOOR_ID  bigint unsigned
6                                    UNIT_TYPE  bigint unsigned
7                        checklist_cat_type_id          tinyint
8                                  DESCRIPTION             text
9                                       STATUS  bigint unsigned
10                       MAINTENANCE_STATUS_ID  bigint unsigned
11                                 location_id  bigint unsigned
12                                   booked_at        timestamp
13                       booked_by_lease_offer     int unsigned
14                    booked_by_lease_contract  bigint unsigned
15                 maintenance_threshold_value     decimal(8,2)
16  maintenance_threshold_value_effective_from             date
17                            projection_value     decimal(8,2)
18             projection_value_effective_from             date
19                                        AREA    decimal(22,2)
20                                 renewal_fee     decimal(8,2)
21                               unit_excluded          tinyint
22                           exclude_reason_id              int
23                                 category_id  bigint unsigned
24                           standard_capacity     varchar(255)
25                            adjustment_limit     varchar(255)
26                              nationality_id           bigint
27                                    religion     varchar(255)
28                                  CREATED_BY  bigint unsigned
29                             LAST_UPDATED_BY  bigint unsigned
30                                  created_at        timestamp
31                                  updated_at        timestamp
32                                  deleted_at        timestamp
33                          unit_qr_unique_key      varchar(15)
34                                is_having_qr          tinyint
35                                    qr_image     varchar(255)

In [90]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime, timedelta

# -------------------------------
# 1️⃣ DB Connection
# -------------------------------
engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

# -------------------------------
# 2️⃣ Load ONLY REAL columns
# -------------------------------
df = pd.read_sql("""
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    STATUS,
    booked_at,
    renewal_fee,
    unit_excluded,
    deleted_at,
    AREA
FROM eq_ls_property_unit
""", engine)

# -------------------------------
# 3️⃣ Date handling
# -------------------------------
df['booked_at'] = pd.to_datetime(df['booked_at'])
df['deleted_at'] = pd.to_datetime(df['deleted_at'])

today = datetime.today()

# Lease age (months)
df['lease_age_months'] = ((today - df['booked_at']).dt.days / 30).fillna(0)

# -------------------------------
# 4️⃣ Renewal & churn logic
# -------------------------------
df['renewal_status'] = np.where(
    df['renewal_fee'] > 0, 'RENEWED', 'NOT_RENEWED'
)

df['churn_flag'] = np.where(
    (df['unit_excluded'] == 1) | (df['deleted_at'].notna()),
    'CHURNED',
    'ACTIVE'
)

# -------------------------------
# 5️⃣ Rent bands (proxy via AREA)
# -------------------------------
df['rent_band'] = pd.cut(
    df['AREA'],
    bins=[0, 500, 1000, 10**9],
    labels=['Low', 'Mid', 'High']
)

# -------------------------------
# 6️⃣ CORE KPIs
# -------------------------------

# Overall Renewal %
overall_renewal = (df['renewal_status'] == 'RENEWED').mean() * 100
print(f"\n🔁 Overall Renewal Rate: {overall_renewal:.2f}%")

# Renewal by Property
renewal_by_property = (
    df.groupby('PROPERTY_ID')['renewal_status']
    .apply(lambda x: (x == 'RENEWED').mean() * 100)
    .round(2)
    .sort_values()
)

print("\n🏢 Lowest Renewal Properties")
print(renewal_by_property.head())

# Renewal by Rent Band
renewal_by_rent_band = (
    df.groupby('rent_band')['renewal_status']
    .apply(lambda x: (x == 'RENEWED').mean() * 100)
    .round(2)
)

print("\n💰 Renewal by Rent Band")
print(renewal_by_rent_band)

# -------------------------------
# 7️⃣ TENURE IMPACT
# -------------------------------
df['tenure_band'] = pd.cut(
    df['lease_age_months'],
    bins=[0, 12, 24, 1000],
    labels=['<1 Year', '1–2 Years', '>2 Years']
)

renewal_by_tenure = (
    df.groupby('tenure_band')['renewal_status']
    .apply(lambda x: (x == 'RENEWED').mean() * 100)
    .round(2)
)

print("\n⏳ Renewal by Tenure")
print(renewal_by_tenure)

# -------------------------------
# 8️⃣ RISK IDENTIFICATION
# -------------------------------
high_risk = df[
    (df['lease_age_months'] > 10) &
    (df['renewal_fee'] == 0) &
    (df['churn_flag'] == 'ACTIVE')
]

print(f"\n⚠️ High Risk Units (Likely to Churn): {len(high_risk)}")

🔁 Overall Renewal Rate: 76.78%

🏢 Lowest Renewal Properties
PROPERTY_ID
5     0.0
4     0.0
11    0.0
6     0.0
20    0.0
Name: renewal_status, dtype: float64

💰 Renewal by Rent Band
rent_band
Low     78.35
Mid     81.38
High    72.54
Name: renewal_status, dtype: float64

⏳ Renewal by Tenure
tenure_band
<1 Year      83.61
1–2 Years      NaN
>2 Years       NaN
Name: renewal_status, dtype: float64

⚠️ High Risk Units (Likely to Churn): 0

C:\Users\harikrishnan\AppData\Local\Temp\ipykernel_19472\1441641304.py:83: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('rent_band')['renewal_status']
C:\Users\harikrishnan\AppData\Local\Temp\ipykernel_19472\1441641304.py:101: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('tenure_band')['renewal_status']

# Which leases expiring in next 30 / 60 / 90 days are high risk?

In [91]:
from datetime import datetime, timedelta

df['expected_lease_end'] = df['booked_at'] + pd.DateOffset(months=12)

today = datetime.today()

def high_risk(days):
    return df[
        (df['expected_lease_end'].between(today, today + timedelta(days=days))) &
        (df['renewal_fee'] == 0) &
        (df['churn_flag'] == 'ACTIVE')
    ]

risk_30 = high_risk(30)
risk_60 = high_risk(60)
risk_90 = high_risk(90)

print("⚠️ High Risk Expiring in 30 days:", len(risk_30))
print("⚠️ High Risk Expiring in 60 days:", len(risk_60))
print("⚠️ High Risk Expiring in 90 days:", len(risk_90))

⚠️ High Risk Expiring in 30 days: 0
⚠️ High Risk Expiring in 60 days: 0
⚠️ High Risk Expiring in 90 days: 0

In [ ]:
2️# Which tenants renewed previously but not now?

In [92]:
renewal_history = (
    df.groupby('unit_id')['renewal_fee']
    .apply(lambda x: (x > 0).sum())
)

df['renewed_before'] = df['unit_id'].map(renewal_history)

lost_renewals = df[
    (df['renewed_before'] > 0) &
    (df['renewal_fee'] == 0)
]

print("🔄 Units renewed previously but not now:", len(lost_renewals))

🔄 Units renewed previously but not now: 0

In [96]:
print(df.columns)

Index(['unit_id', 'PROPERTY_ID', 'STATUS', 'booked_at', 'renewal_fee',
       'unit_excluded', 'deleted_at', 'AREA', 'lease_age_months',
       'renewal_status', 'churn_flag', 'rent_band', 'tenure_band',
       'expected_lease_end', 'renewed_before'],
      dtype='object')

In [97]:
renewal_by_property = (
    df.groupby('PROPERTY_ID')['renewal_status']
    .apply(lambda x: (x == 'RENEWED').mean() * 100)
    .round(2)
    .sort_values()
)

print("🏢 Renewal Rate by Property")
print(renewal_by_property)

🏢 Renewal Rate by Property
PROPERTY_ID
5        0.0
4        0.0
11       0.0
6        0.0
20       0.0
       ...
207    100.0
208    100.0
210    100.0
211    100.0
212    100.0
Name: renewal_status, Length: 137, dtype: float64

In [100]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime, timedelta

engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

df = pd.read_sql("""
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    booked_at,
    renewal_fee,
    unit_excluded,
    deleted_at
FROM eq_ls_property_unit
WHERE booked_at IS NOT NULL
""", engine)

df['booked_at'] = pd.to_datetime(df['booked_at'])
df['deleted_at'] = pd.to_datetime(df['deleted_at'])

In [101]:
today = datetime.today()

# Assume 12-month lease
df['expected_lease_end'] = df['booked_at'] + pd.DateOffset(months=12)

df['is_active'] = np.where(
    (df['unit_excluded'] == 0) & (df['deleted_at'].isna()),
    1, 0
)

df['high_risk_flag'] = np.where(
    (df['expected_lease_end'] <= today + timedelta(days=90)) &
    (df['renewal_fee'] == 0) &
    (df['is_active'] == 1),
    1, 0
)

In [102]:
risk_by_property = (
    df.groupby('PROPERTY_ID')
    .agg(
        total_units=('unit_id', 'count'),
        high_risk_units=('high_risk_flag', 'sum')
    )
)

risk_by_property['risk_percentage'] = (
    risk_by_property['high_risk_units'] /
    risk_by_property['total_units'] * 100
).round(2)

In [103]:
top_10_risk_properties = (
    risk_by_property
    .sort_values('risk_percentage', ascending=False)
    .head(10)
)

print("🚨 TOP 10 HIGH-RISK PROPERTIES")
print(top_10_risk_properties)

🚨 TOP 10 HIGH-RISK PROPERTIES
             total_units  high_risk_units  risk_percentage
PROPERTY_ID
3                      2                0              0.0
4                      3                0              0.0
6                      2                0              0.0
9                      3                0              0.0
11                     3                0              0.0
14                     1                0              0.0
15                     1                0              0.0
18                    12                0              0.0
22                     3                0              0.0
24                     6                0              0.0

# Rent vs Market Benchmark

In [104]:
df_rent = pd.read_sql("""
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    projection_value AS unit_rent
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
""", engine)

# Market benchmark = median rent per property
market_rent = (
    df_rent.groupby('PROPERTY_ID')['unit_rent']
    .median()
    .reset_index()
    .rename(columns={'unit_rent': 'market_rent'})
)

df_rent = df_rent.merge(market_rent, on='PROPERTY_ID', how='left')

df_rent['rent_gap_pct'] = (
    (df_rent['unit_rent'] - df_rent['market_rent']) /
    df_rent['market_rent'] * 100
).round(2)

print("📊 Rent vs Market Benchmark")
print(df_rent[['PROPERTY_ID','unit_rent','market_rent','rent_gap_pct']].head())

📊 Rent vs Market Benchmark
   PROPERTY_ID  unit_rent  market_rent  rent_gap_pct
0            6       10.0         10.0           0.0
1            9    60000.0      60000.0           0.0
2            5        9.0          9.0           0.0
3            9    60000.0      60000.0           0.0
4            9    60000.0      60000.0           0.0

# Detect Discounted Renewals

In [105]:
df_discount = pd.read_sql("""
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    renewal_fee
FROM eq_ls_property_unit
WHERE renewal_fee IS NOT NULL AND renewal_fee > 0
""", engine)

df_discount = df_discount.merge(market_rent, on='PROPERTY_ID', how='left')

df_discount['discount_pct'] = (
    (df_discount['market_rent'] - df_discount['renewal_fee']) /
    df_discount['market_rent'] * 100
).round(2)

discounted_units = df_discount[df_discount['discount_pct'] > 5]

print("🎯 Discounted Renewals (Retention Strategy)")
print(discounted_units.head())

🎯 Discounted Renewals (Retention Strategy)
   unit_id  PROPERTY_ID  renewal_fee  market_rent  discount_pct
1      323           77        250.0       5000.0          95.0
2      381           85       1000.0     250000.0          99.6
3      382           86        500.0      10000.0          95.0
4      383           86        500.0      10000.0          95.0
5      384           86        500.0      10000.0          95.0

# Renewal vs Market Alignment

In [106]:
df_alignment = df_discount.copy()

df_alignment['pricing_alignment'] = np.select(
    [
        df_alignment['renewal_fee'] < df_alignment['market_rent'] * 0.95,
        df_alignment['renewal_fee'] > df_alignment['market_rent'] * 1.05
    ],
    [
        'Below Market',
        'Above Market'
    ],
    default='Market Aligned'
)

alignment_summary = df_alignment['pricing_alignment'].value_counts()

print("📈 Renewal Pricing Alignment Summary")
print(alignment_summary)

📈 Renewal Pricing Alignment Summary
pricing_alignment
Below Market      1165
Above Market        64
Market Aligned      16
Name: count, dtype: int64

In [111]:
from datetime import datetime

In [114]:
today = datetime.today()

In [119]:
query = """
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS`,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
""",

In [2]:
query = """
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS occupancy_status,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
""",

In [127]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

query = """
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS occupancy_status,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
""", 

df['booked_at'] = pd.to_datetime(df['booked_at'], errors='coerce')


today = datetime.today()

print(df.head())

   unit_id  PROPERTY_ID           booked_at  renewal_fee  unit_excluded  \
0       12            6 2025-05-06 11:17:46          NaN              0
1       13            9 2025-05-08 10:38:35          NaN              0
2       15            9 2025-05-08 11:40:40          NaN              0
3       18            6 2025-05-07 13:26:04          NaN              0
4       21           15 2025-05-08 07:28:21          NaN              0

  deleted_at  expected_lease_end  is_active  high_risk_flag
0        NaT 2026-05-06 11:17:46          1               0
1        NaT 2026-05-08 10:38:35          1               0
2        NaT 2026-05-08 11:40:40          1               0
3        NaT 2026-05-07 13:26:04          1               0
4        NaT 2026-05-08 07:28:21          1               0

In [3]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from datetime import datetime

engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

query = """
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS occupancy_status,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
""", 

today = datetime.today()

In [4]:
df = query = """
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    STATUS,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
""",

In [6]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

query = """
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS status,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
"""

df = pd.read_sql(query, engine)

df['booked_at'] = pd.to_datetime(df['booked_at'], errors='coerce')
df['move_out_date'] = pd.to_datetime(df['move_out_date'], errors='coerce')

today = datetime.today()

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'move_out_date' in 'field list'")
[SQL:
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS status,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

query = """
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS status,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
"""

df = pd.read_sql(query, engine)

df['booked_at'] = pd.to_datetime(df['booked_at'], errors='coerce')
df['move_out_date'] = pd.to_datetime(df['move_out_date'], errors='coerce')

today = datetime.today()

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'move_out_date' in 'field list'")
[SQL:
SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS status,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [144]:
print(type(query))
print(query)

<class 'str'>

SELECT
    ID AS unit_id,
    PROPERTY_ID,
    `STATUS` AS status,
    booked_at,
    move_out_date,
    projection_value
FROM eq_ls_property_unit
WHERE projection_value IS NOT NULL