In [9]:
%pip install sqlalchemy pymysql pandas

Requirement already satisfied: sqlalchemy in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (2.0.45)
Requirement already satisfied: pymysql in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (1.1.2)
Requirement already satisfied: pandas in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (2.3.3)
Requirement already satisfied: greenlet>=1 in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\harikrishnan\downloads\analytics\curve\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [56]:
import pandas as pd
from sqlalchemy import create_engine,text

In [57]:
engine = create_engine(
    "mysql+pymysql://root:P%40ssme%4012345@192.168.1.206:3309/equal_react_curve"
)

In [71]:
vacancy_loss_sql = text("""
SELECT
    SUM(COALESCE(c.total_amount, 0)) AS vacancy_loss
FROM eq_ls_property_unit pu
LEFT JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
WHERE pu.booked_at IS NULL
  AND pu.unit_excluded = 0;
""")

with engine.connect() as conn:
    vacancy_loss = conn.execute(vacancy_loss_sql).scalar()

print("1️⃣ Vacancy Revenue Loss:", vacancy_loss)

1️⃣ Vacancy Revenue Loss: 23621178.00

In [72]:
vacancy_by_property_sql = text("""
SELECT
    pu.PROPERTY_ID,
    SUM(COALESCE(c.total_amount, 0)) AS vacancy_loss
FROM eq_ls_property_unit pu
LEFT JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
WHERE pu.booked_at IS NULL
  AND pu.unit_excluded = 0
GROUP BY pu.PROPERTY_ID
ORDER BY vacancy_loss DESC;
""")

with engine.connect() as conn:
    vacancy_by_property = conn.execute(vacancy_by_property_sql).mappings().all()

print("\n2️⃣ Properties with highest vacancy loss:")
for row in vacancy_by_property:
    print(row)

2️⃣ Properties with highest vacancy loss:
{'PROPERTY_ID': 32, 'vacancy_loss': Decimal('9000000.00')}
{'PROPERTY_ID': 139, 'vacancy_loss': Decimal('2820000.00')}
{'PROPERTY_ID': 78, 'vacancy_loss': Decimal('2250000.00')}
{'PROPERTY_ID': 77, 'vacancy_loss': Decimal('1536000.00')}
{'PROPERTY_ID': 102, 'vacancy_loss': Decimal('800000.00')}
{'PROPERTY_ID': 16, 'vacancy_loss': Decimal('600000.00')}
{'PROPERTY_ID': 90, 'vacancy_loss': Decimal('540000.00')}
{'PROPERTY_ID': 59, 'vacancy_loss': Decimal('485200.00')}
{'PROPERTY_ID': 138, 'vacancy_loss': Decimal('477000.00')}
{'PROPERTY_ID': 129, 'vacancy_loss': Decimal('455000.00')}
{'PROPERTY_ID': 101, 'vacancy_loss': Decimal('365000.00')}
{'PROPERTY_ID': 118, 'vacancy_loss': Decimal('362000.00')}
{'PROPERTY_ID': 97, 'vacancy_loss': Decimal('320000.00')}
{'PROPERTY_ID': 157, 'vacancy_loss': Decimal('309000.00')}
{'PROPERTY_ID': 201, 'vacancy_loss': Decimal('225000.00')}
{'PROPERTY_ID': 158, 'vacancy_loss': Decimal('195000.00')}
{'PROPERTY_ID': 87, 'vacancy_loss': Decimal('190000.00')}
{'PROPERTY_ID': 131, 'vacancy_loss': Decimal('180000.00')}
{'PROPERTY_ID': 180, 'vacancy_loss': Decimal('161000.00')}
{'PROPERTY_ID': 142, 'vacancy_loss': Decimal('151200.00')}
{'PROPERTY_ID': 103, 'vacancy_loss': Decimal('150200.00')}
{'PROPERTY_ID': 160, 'vacancy_loss': Decimal('125000.00')}
{'PROPERTY_ID': 121, 'vacancy_loss': Decimal('120000.00')}
{'PROPERTY_ID': 182, 'vacancy_loss': Decimal('106000.00')}
{'PROPERTY_ID': 156, 'vacancy_loss': Decimal('100344.00')}
{'PROPERTY_ID': 71, 'vacancy_loss': Decimal('90000.00')}
{'PROPERTY_ID': 170, 'vacancy_loss': Decimal('73000.00')}
{'PROPERTY_ID': 29, 'vacancy_loss': Decimal('71100.00')}
{'PROPERTY_ID': 86, 'vacancy_loss': Decimal('70000.00')}
{'PROPERTY_ID': 89, 'vacancy_loss': Decimal('67500.00')}
{'PROPERTY_ID': 53, 'vacancy_loss': Decimal('61000.00')}
{'PROPERTY_ID': 9, 'vacancy_loss': Decimal('60000.00')}
{'PROPERTY_ID': 93, 'vacancy_loss': Decimal('60000.00')}
{'PROPERTY_ID': 24, 'vacancy_loss': Decimal('51000.00')}
{'PROPERTY_ID': 149, 'vacancy_loss': Decimal('51000.00')}
{'PROPERTY_ID': 11, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 120, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 135, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 132, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 136, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 171, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 2, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 193, 'vacancy_loss': Decimal('50000.00')}
{'PROPERTY_ID': 96, 'vacancy_loss': Decimal('46000.00')}
{'PROPERTY_ID': 128, 'vacancy_loss': Decimal('46000.00')}
{'PROPERTY_ID': 153, 'vacancy_loss': Decimal('40000.00')}
{'PROPERTY_ID': 147, 'vacancy_loss': Decimal('34200.00')}
{'PROPERTY_ID': 150, 'vacancy_loss': Decimal('30000.00')}
{'PROPERTY_ID': 154, 'vacancy_loss': Decimal('30000.00')}
{'PROPERTY_ID': 30, 'vacancy_loss': Decimal('29200.00')}
{'PROPERTY_ID': 65, 'vacancy_loss': Decimal('25000.00')}
{'PROPERTY_ID': 74, 'vacancy_loss': Decimal('21000.00')}
{'PROPERTY_ID': 184, 'vacancy_loss': Decimal('20001.00')}
{'PROPERTY_ID': 46, 'vacancy_loss': Decimal('17400.00')}
{'PROPERTY_ID': 52, 'vacancy_loss': Decimal('16200.00')}
{'PROPERTY_ID': 27, 'vacancy_loss': Decimal('15000.00')}
{'PROPERTY_ID': 183, 'vacancy_loss': Decimal('15000.00')}
{'PROPERTY_ID': 39, 'vacancy_loss': Decimal('14400.00')}
{'PROPERTY_ID': 56, 'vacancy_loss': Decimal('10200.00')}
{'PROPERTY_ID': 31, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 67, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 123, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 188, 'vacancy_loss': Decimal('10000.00')}
{'PROPERTY_ID': 173, 'vacancy_loss': Decimal('9000.00')}
{'PROPERTY_ID': 14, 'vacancy_loss': Decimal('7300.00')}
{'PROPERTY_ID': 82, 'vacancy_loss': Decimal('6000.00')}
{'PROPERTY_ID': 50, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 23, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 92, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 108, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 203, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 202, 'vacancy_loss': Decimal('5000.00')}
{'PROPERTY_ID': 18, 'vacancy_loss': Decimal('4000.00')}
{'PROPERTY_ID': 37, 'vacancy_loss': Decimal('4000.00')}
{'PROPERTY_ID': 85, 'vacancy_loss': Decimal('3500.00')}
{'PROPERTY_ID': 70, 'vacancy_loss': Decimal('3333.00')}
{'PROPERTY_ID': 73, 'vacancy_loss': Decimal('3200.00')}
{'PROPERTY_ID': 63, 'vacancy_loss': Decimal('3100.00')}
{'PROPERTY_ID': 159, 'vacancy_loss': Decimal('2500.00')}
{'PROPERTY_ID': 54, 'vacancy_loss': Decimal('2200.00')}
{'PROPERTY_ID': 3, 'vacancy_loss': Decimal('2000.00')}
{'PROPERTY_ID': 28, 'vacancy_loss': Decimal('1700.00')}
{'PROPERTY_ID': 174, 'vacancy_loss': Decimal('1500.00')}
{'PROPERTY_ID': 49, 'vacancy_loss': Decimal('1300.00')}
{'PROPERTY_ID': 48, 'vacancy_loss': Decimal('1200.00')}
{'PROPERTY_ID': 58, 'vacancy_loss': Decimal('1200.00')}
{'PROPERTY_ID': 192, 'vacancy_loss': Decimal('1200.00')}
{'PROPERTY_ID': 98, 'vacancy_loss': Decimal('1100.00')}
{'PROPERTY_ID': 26, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 80, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 144, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 143, 'vacancy_loss': Decimal('1000.00')}
{'PROPERTY_ID': 68, 'vacancy_loss': Decimal('500.00')}
{'PROPERTY_ID': 6, 'vacancy_loss': Decimal('100.00')}
{'PROPERTY_ID': 75, 'vacancy_loss': Decimal('100.00')}
{'PROPERTY_ID': 44, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 51, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 66, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 72, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 76, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 109, 'vacancy_loss': Decimal('0.00')}
{'PROPERTY_ID': 204, 'vacancy_loss': Decimal('0.00')}

In [73]:
delayed_collection_sql = text("""
SELECT
    SUM(total_amount - COALESCE(APPROVED_AMOUNT, 0)) AS delayed_collection_loss
FROM eq_ls_property_unit_charges
WHERE CHARGE_CODE = 1
  AND created_at < CURRENT_DATE
  AND deleted_at IS NULL
  AND (APPROVED_AMOUNT IS NULL OR APPROVED_AMOUNT < total_amount);
""")

with engine.connect() as conn:
    delayed_loss = conn.execute(delayed_collection_sql).scalar()

print("\n3️⃣ Delayed Collection Loss:", delayed_loss)

3️⃣ Delayed Collection Loss: 3762366.00

In [74]:
unpaid_moveout_sql = text("""
SELECT
    pu.ID AS unit_id,
    pu.PROPERTY_ID,
    SUM(c.total_amount - COALESCE(c.APPROVED_AMOUNT, 0)) AS unpaid_due
FROM eq_ls_property_unit pu
JOIN eq_ls_property_unit_charges c
    ON pu.ID = c.PROPERTY_UNIT
WHERE pu.booked_at IS NULL
  AND c.deleted_at IS NULL
GROUP BY pu.ID, pu.PROPERTY_ID
HAVING unpaid_due > 0
ORDER BY unpaid_due DESC;
""")

with engine.connect() as conn:
    unpaid_units = conn.execute(unpaid_moveout_sql).mappings().all()

print("\n4️⃣ Units with unpaid dues at move-out:")
for row in unpaid_units:
    print(row)

4️⃣ Units with unpaid dues at move-out:
{'unit_id': 25, 'PROPERTY_ID': 16, 'unpaid_due': Decimal('510000.00')}
{'unit_id': 847, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('230000.00')}
{'unit_id': 1255, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1256, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1257, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1258, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1259, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1260, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1261, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 1262, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('51750.00')}
{'unit_id': 26, 'PROPERTY_ID': 16, 'unpaid_due': Decimal('50000.00')}
{'unit_id': 875, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('50000.00')}
{'unit_id': 382, 'PROPERTY_ID': 86, 'unpaid_due': Decimal('45000.00')}
{'unit_id': 941, 'PROPERTY_ID': 87, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 977, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 980, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 981, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 982, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 983, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 984, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 985, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 986, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 987, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('35000.00')}
{'unit_id': 874, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('30000.00')}
{'unit_id': 989, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 990, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 991, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 992, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 993, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 994, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 995, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 996, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 998, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 999, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1000, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1001, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1002, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1003, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1004, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1005, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1006, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1007, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1008, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1009, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1010, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1011, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1012, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1013, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1014, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1015, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1016, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1017, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1018, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1019, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1020, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1021, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1022, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1023, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1024, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1025, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1026, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 1027, 'PROPERTY_ID': 139, 'unpaid_due': Decimal('25000.00')}
{'unit_id': 266, 'PROPERTY_ID': 74, 'unpaid_due': Decimal('20100.00')}
{'unit_id': 872, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1123, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1125, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1127, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1130, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1131, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('20000.00')}
{'unit_id': 1488, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('15000.00')}
{'unit_id': 1489, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('15000.00')}
{'unit_id': 1490, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('15000.00')}
{'unit_id': 319, 'PROPERTY_ID': 46, 'unpaid_due': Decimal('14500.00')}
{'unit_id': 1228, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('13500.00')}
{'unit_id': 1585, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1586, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1587, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1588, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 1589, 'PROPERTY_ID': 201, 'unpaid_due': Decimal('13250.00')}
{'unit_id': 169, 'PROPERTY_ID': 29, 'unpaid_due': Decimal('12000.00')}
{'unit_id': 1482, 'PROPERTY_ID': 2, 'unpaid_due': Decimal('11000.00')}
{'unit_id': 689, 'PROPERTY_ID': 103, 'unpaid_due': Decimal('10500.00')}
{'unit_id': 24, 'PROPERTY_ID': 16, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 862, 'PROPERTY_ID': 120, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1108, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1109, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1110, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1196, 'PROPERTY_ID': 156, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 1280, 'PROPERTY_ID': 142, 'unpaid_due': Decimal('10000.00')}
{'unit_id': 932, 'PROPERTY_ID': 123, 'unpaid_due': Decimal('9000.00')}
{'unit_id': 51, 'PROPERTY_ID': 11, 'unpaid_due': Decimal('8500.00')}
{'unit_id': 1223, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('8250.00')}
{'unit_id': 1225, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('8250.00')}
{'unit_id': 1226, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('8250.00')}
{'unit_id': 845, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('8000.00')}
{'unit_id': 846, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('8000.00')}
{'unit_id': 692, 'PROPERTY_ID': 104, 'unpaid_due': Decimal('7500.00')}
{'unit_id': 374, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('7400.00')}
{'unit_id': 900, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('7000.00')}
{'unit_id': 901, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('7000.00')}
{'unit_id': 1331, 'PROPERTY_ID': 149, 'unpaid_due': Decimal('7000.00')}
{'unit_id': 146, 'PROPERTY_ID': 37, 'unpaid_due': Decimal('6900.00')}
{'unit_id': 696, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 697, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 698, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 699, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 700, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 701, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 702, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 703, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 704, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 705, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 706, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 707, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 708, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 709, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 710, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 711, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 712, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 713, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 714, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 715, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 716, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 717, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 718, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 719, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 720, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 721, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 722, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 723, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 724, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 725, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 726, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 727, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 728, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 729, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 730, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 731, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 732, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 733, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 734, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 735, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 736, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 737, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 738, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 739, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 740, 'PROPERTY_ID': 78, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 818, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('6000.00')}
{'unit_id': 1229, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('5400.00')}
{'unit_id': 47, 'PROPERTY_ID': 20, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 160, 'PROPERTY_ID': 53, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 186, 'PROPERTY_ID': 67, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 853, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 876, 'PROPERTY_ID': 131, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 882, 'PROPERTY_ID': 128, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 935, 'PROPERTY_ID': 135, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 1310, 'PROPERTY_ID': 142, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 1377, 'PROPERTY_ID': 156, 'unpaid_due': Decimal('5000.00')}
{'unit_id': 181, 'PROPERTY_ID': 65, 'unpaid_due': Decimal('4500.00')}
{'unit_id': 176, 'PROPERTY_ID': 58, 'unpaid_due': Decimal('4200.00')}
{'unit_id': 316, 'PROPERTY_ID': 28, 'unpaid_due': Decimal('4200.00')}
{'unit_id': 263, 'PROPERTY_ID': 70, 'unpaid_due': Decimal('4100.00')}
{'unit_id': 156, 'PROPERTY_ID': 50, 'unpaid_due': Decimal('4000.00')}
{'unit_id': 369, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3900.00')}
{'unit_id': 370, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3900.00')}
{'unit_id': 178, 'PROPERTY_ID': 63, 'unpaid_due': Decimal('3700.00')}
{'unit_id': 244, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3600.00')}
{'unit_id': 272, 'PROPERTY_ID': 71, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 273, 'PROPERTY_ID': 71, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1183, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1184, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1185, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1186, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1187, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 1190, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('3500.00')}
{'unit_id': 371, 'PROPERTY_ID': 39, 'unpaid_due': Decimal('3300.00')}
{'unit_id': 159, 'PROPERTY_ID': 53, 'unpaid_due': Decimal('3000.00')}
{'unit_id': 207, 'PROPERTY_ID': 3, 'unpaid_due': Decimal('3000.00')}
{'unit_id': 275, 'PROPERTY_ID': 56, 'unpaid_due': Decimal('2700.00')}
{'unit_id': 1171, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1172, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1173, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1174, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1175, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1176, 'PROPERTY_ID': 154, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 1386, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('2500.00')}
{'unit_id': 405, 'PROPERTY_ID': 89, 'unpaid_due': Decimal('2450.00')}
{'unit_id': 1230, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1265, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1267, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1268, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1269, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1270, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1271, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1272, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1273, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1274, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1321, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1322, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1323, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1324, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1325, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1326, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1327, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1328, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('2250.00')}
{'unit_id': 1311, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1312, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1313, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1314, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1315, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1318, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 1319, 'PROPERTY_ID': 157, 'unpaid_due': Decimal('2200.00')}
{'unit_id': 848, 'PROPERTY_ID': 118, 'unpaid_due': Decimal('2111.00')}
{'unit_id': 1159, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1160, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1161, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1162, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1163, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1164, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1165, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 1166, 'PROPERTY_ID': 153, 'unpaid_due': Decimal('2100.00')}
{'unit_id': 234, 'PROPERTY_ID': 73, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 866, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 881, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1089, 'PROPERTY_ID': 149, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1091, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1092, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1093, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1094, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1095, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1096, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1097, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1098, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1099, 'PROPERTY_ID': 129, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1277, 'PROPERTY_ID': 142, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 1428, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('2000.00')}
{'unit_id': 179, 'PROPERTY_ID': 63, 'unpaid_due': Decimal('1850.00')}
{'unit_id': 1241, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1243, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1245, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1246, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1247, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1248, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1249, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1250, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1251, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1252, 'PROPERTY_ID': 158, 'unpaid_due': Decimal('1753.00')}
{'unit_id': 1417, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('1730.00')}
{'unit_id': 233, 'PROPERTY_ID': 73, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1135, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1136, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1137, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1138, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1139, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1140, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1141, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1142, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1538, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 1635, 'PROPERTY_ID': 202, 'unpaid_due': Decimal('1500.00')}
{'unit_id': 265, 'PROPERTY_ID': 74, 'unpaid_due': Decimal('1400.00')}
{'unit_id': 1400, 'PROPERTY_ID': 180, 'unpaid_due': Decimal('1400.00')}
{'unit_id': 190, 'PROPERTY_ID': 46, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1352, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1353, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1354, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1300.00')}
{'unit_id': 1080, 'PROPERTY_ID': 101, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1212, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1213, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1214, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1215, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1216, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1217, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1218, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1219, 'PROPERTY_ID': 138, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1356, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1357, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1358, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}
{'unit_id': 1359, 'PROPERTY_ID': 170, 'unpaid_due': Decimal('1250.00')}

In [77]:
from sqlalchemy import text

deposit_writeoff_sql = text("""
SELECT
    SUM(total_amount - COALESCE(APPROVED_AMOUNT, 0)) AS deposit_written_off
FROM eq_ls_property_unit_charges
WHERE CHARGE_CODE = 2
  AND deleted_at IS NULL
  AND (APPROVED_AMOUNT IS NULL OR APPROVED_AMOUNT < total_amount);
""")

with engine.connect() as conn:
    deposit_loss = conn.execute(deposit_writeoff_sql).scalar()

print("5️⃣ Deposit Written-off Amount:", deposit_loss)

5️⃣ Deposit Written-off Amount: 3133545.00

In [78]:
df_delayed['delayed_loss'].sum()

np.float64(3177066.0)

In [23]:
query = """
SELECT
    pu.ID AS unit_id,
    pu.PROPERTY_ID,
    COALESCE(c.total_amount, 0) AS renewal_gap_loss
FROM eq_ls_property_unit pu
LEFT JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
WHERE pu.booked_at IS NULL
  AND pu.unit_excluded = 0
  AND pu.STATUS = 1;
"""
df_renewal_gap = pd.read_sql(query, engine)
df_renewal_gap

     unit_id  PROPERTY_ID  renewal_gap_loss
0        172           52            1000.0
1        175           58               0.0
2        177           56            5000.0
3        179           63             100.0
4        181           65            5000.0
..       ...          ...               ...
451     1613          203            5000.0
452     1631          204               0.0
453     1632          202            5000.0
454     1635          202            5000.0
455     1642          183            5000.0

[456 rows x 3 columns]

In [24]:
df_renewal_gap['renewal_gap_loss'].sum()

np.float64(11712277.0)

# Vacancy % = Vacant Units / Total Units × 100

In [25]:
query = """
SELECT
    COUNT(*) AS total_units,
    SUM(CASE WHEN booked_at IS NULL THEN 1 ELSE 0 END) AS vacant_units,
    ROUND(
        SUM(CASE WHEN booked_at IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS vacancy_percentage
FROM eq_ls_property_unit
WHERE unit_excluded = 0;
"""
df_vacancy = pd.read_sql(query, engine)
df_vacancy

   total_units  vacant_units  vacancy_percentage
0         1566         615.0               39.27

In [26]:
query = """
WITH market_rent AS (
    SELECT
        pu.UNIT_TYPE,
        AVG(c.total_amount) AS avg_market_rent
    FROM eq_ls_property_unit pu
    JOIN eq_ls_property_unit_charges c
        ON pu.ID = c.PROPERTY_UNIT
    WHERE c.CHARGE_CODE = 1
      AND c.deleted_at IS NULL
    GROUP BY pu.UNIT_TYPE
)
SELECT
    pu.ID AS unit_id,
    pu.UNIT_TYPE,
    put.NAME AS unit_type_name,
    c.total_amount AS actual_rent,
    mr.avg_market_rent,
    (mr.avg_market_rent - c.total_amount) AS rent_leakage
FROM eq_ls_property_unit pu
JOIN eq_ls_property_unit_charges c
    ON c.ID = (
        SELECT c2.ID
        FROM eq_ls_property_unit_charges c2
        WHERE c2.PROPERTY_UNIT = pu.ID
          AND c2.CHARGE_CODE = 1
          AND c2.deleted_at IS NULL
        ORDER BY c2.created_at DESC
        LIMIT 1
    )
JOIN market_rent mr
    ON pu.UNIT_TYPE = mr.UNIT_TYPE
JOIN eq_ls_property_unit_type put
    ON pu.UNIT_TYPE = put.ID
WHERE c.total_amount < mr.avg_market_rent;
"""
df_below_market = pd.read_sql(query, engine)
df_below_market

,unit_id,UNIT_TYPE,unit_type_name,actual_rent,avg_market_rent,rent_leakage
0,14,1,"1-Bedroom, 1-Baths",2000.0,25317.250591,23317.250591
1,19,1,"1-Bedroom, 1-Baths",2300.0,25317.250591,23017.250591
2,20,1,"1-Bedroom, 1-Baths",5000.0,25317.250591,20317.250591
3,21,1,"1-Bedroom, 1-Baths",5000.0,25317.250591,20317.250591
4,23,1,"1-Bedroom, 1-Baths",3000.0,25317.250591,22317.250591
...,...,...,...,...,...,...
843,1526,40,2BHK Apartment,10000.0,70760.000000,60760.000000
844,1528,40,2BHK Apartment,7000.0,70760.000000,63760.000000
845,1535,40,2BHK Apartment,5000.0,70760.000000,65760.000000
846,1536,40,2BHK Apartment,5000.0,70760.000000,65760.000000
847,1537,40,2BHK Apartment,5000.0,70760.000000,65760.000000

In [40]:
df_below_market['rent_leakage'].sum()

np.float64(22994658.380225003)